num1 = float(input("Enter the 1st number: "))
num2 = float(input("Enter the 2nd number: "))
num3 = float(input("Enter the 3rd number: "))
num4 = float(input("Enter the 4th number: "))
num5 = float(input("Enter the 5th number: "))
num6 = float(input("Enter the 6th number: "))
num7 = float(input("Enter the 7th number: "))
num8 = float(input("Enter the 8th number: "))
num9 = float(input("Enter the 9th number: "))
num10 = float(input("Enter the 10th number: "))
num11 = float(input("Enter the 11th number: "))
sum = (num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10 + num11)
average = (num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10 + num11) / 11
print(sum)
print(average)
